# Generated by Django 3.1.1 on 2020-09-17 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nombre del curso:')),
                ('description', models.TextField(verbose_name='Descripción del curso')),
                ('duration', models.PositiveSmallIntegerField(verbose_name='Duración en horas:')),
                ('url', models.URLField(verbose_name='URL del curso')),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
    ]
